import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Kuti - Home page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


<header className="mt-[60px]">
  <div className='flex  justify-center'>
    <div className='w-[500px] ml-[150px] mt-[80px]'>
      <h1 className='font-bold text-6xl mb-[20px]'>More than just shorter links</h1>
      <p>Build your brand recognition and get detailed insights,total clicks of your clicks performance</p>

      <div>
        <button className='text-white bg-[#2BD0D0] w-[200px] p-2'>Get Started</button>
      </div>
      </div>
    <div>
      <Image src="/illustration-working.svg" width="500px" height="400px" alt="illustration"></Image>
    </div>
  </div>
</header>


<div className='h-[600px] bg-[#EFF1F7] bigContainer mt-[60px] relative'>
  <div className='inputContainer bg-[#3A3054] w-[70%] mx-auto flex items-center justify-around h-[80px] p-4 shadow absolute -top-[50px] left-[200px] mb-[350px]'  style={{borderRadius:'10px'}}>
    <input type="text" placeholder='Enter Links' className='w-[700px] p-2'/>
    <button className='text-white bg-[#2BD0D0] w-[200px] p-2'>Shorten</button>

  </div>
<br/><br/><br/><br/><br/><br/><br/><br/>

  <div className='mt-[50px] flex flex-col items-center justify-center'>
    <div><h1 className='text-center font-bold text-4xl'>ADVANCED STATISTICS</h1>
    <p className='text-center'>Track how your links are performings</p></div>
  </div>

</div>

     


    
    </>
  )
}
